
SELECT c.ID
FROM ECOLI_DATA a
JOIN ECOLI_DATA b ON a.ID = b.PARENT_ID
JOIN ECOLI_DATA c ON b.ID = c.PARENT_ID
WHERE a.PARENT_ID is null
ORDER BY c.ID












-- 코드를 작성해주세요
# SELECT T.ID
# FROM ECOLI_DATA F
#      INNER JOIN ECOLI_DATA S ON F.ID = S.PARENT_ID 
#      INNER JOIN ECOLI_DATA T ON S.ID = T.PARENT_ID
# WHERE F.PARENT_ID IS NULL
# ORDER BY T.ID ASC