-- 코드를 작성해주세요
SELECT ed.ID, IFNULL(cd.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA ed
LEFT JOIN (SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
            FROM ECOLI_DATA
            GROUP BY PARENT_ID) AS cd
ON ed.ID = cd.PARENT_ID
ORDER BY ed.ID