-- 코드를 입력하세요
SELECT fp.CATEGORY, fp.PRICE AS MAX_PRICE, fp.PRODUCT_NAME
FROM FOOD_PRODUCT fp
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY in ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS MAX_PRODUCTS
ON fp.CATEGORY = MAX_PRODUCTS.CATEGORY AND fp.PRICE = MAX_PRODUCTS.MAX_PRICE
WHERE fp.CATEGORY in ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC